In [10]:
import numpy as np
import pandas as pd
import re

from nltk.tokenize import word_tokenize

In [23]:
csv = 'maltaindependent_cleaned.csv'

In [24]:
df = pd.read_csv(csv)

In [26]:
with open('locations.txt', 'r') as f:
    locations = f.read().split('\n')

locations = [location.lower() for location in locations]

In [27]:
def contains_location(text):
    for word in word_tokenize(text):
        if word.lower() in locations:
            return True
    return False

In [39]:
# filter out articles that don't contain a location
df['body'] = df['body'].astype(str)
df2 = df[df['body'].apply(contains_location)]

In [41]:
# filter out articles that don't contain a location
# df2 = df[df['body'].apply(contains_location)]

# add entities column type string
df2['location'] = ''
df2['entities'] = ''

for i, row in df2.iterrows():
    # print(i)
    body = row['body']
    tokens = word_tokenize(body)
    location = []
    entities = []

    offset = 0
    for j, token in enumerate(tokens):
        if token.lower() in locations:
            location.append(token)
            # get character index in body
            start = ' '.join(tokens).find(token, offset)
            end = start + len(token)
            offset = end
            entities.append((start, end, 'LOC'))

    df2.at[i, 'body'] = ' '.join(word_tokenize(body))
    df2.at[i, 'location'] = str(location)
    df2.at[i, 'entities'] = str(entities)

c:\Programming\Python\Environments\anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
c:\Programming\Python\Environments\anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [43]:
df2

,link,title,date,body,image,location,entities
0,https://www.independent.com.mt/articles/2023-0...,When we are conscious that we shouldn’t be dri...,22/05/2023 19:53,When we are conscious that we shouldn ’ t be d...,https://www.independent.com.mt/file.aspx?f=226519,['Attard'],"[(523, 529, 'LOC')]"
4,https://www.independent.com.mt/articles/2023-0...,Parents guilty of seven-year-old daughter's de...,22/05/2023 17:56,A court has found the parents of Victoria Aluk...,https://www.independent.com.mt/file.aspx?f=138507,"['Żabbar', 'Żabbar', 'Żabbar']","[(1542, 1548, 'LOC'), (3231, 3237, 'LOC'), (34..."
10,https://www.independent.com.mt/articles/2023-0...,New active ageing centre opened in Pembroke,22/05/2023 13:54,A new active ageing centre was opened in Pembr...,https://www.independent.com.mt/file.aspx?f=232773,"['Pembroke', 'Pembroke']","[(41, 49, 'LOC'), (218, 226, 'LOC')]"
11,https://www.independent.com.mt/articles/2023-0...,"Malta must be proactive, not reactive in desig...",22/05/2023 13:39,Malta must be proactive rather than reactive i...,https://www.independent.com.mt/file.aspx?f=225016,"['Attard', 'Qormi', 'Birkirkara', 'Luqa']","[(906, 912, 'LOC'), (1765, 1770, 'LOC'), (1836..."
13,https://www.independent.com.mt/articles/2023-0...,You were a beautiful flower – father of teenag...,22/05/2023 11:48,You were a beautiful flower the distraught fat...,https://www.independent.com.mt/file.aspx?f=232770,['Attard'],"[(94, 100, 'LOC')]"
...,...,...,...,...,...,...,...
6382,https://www.independent.com.mt/articles/2022-0...,€12 million investment in Ħal Far SME facility,24/01/2022 15:23,The government announced today that €12 millio...,https://www.independent.com.mt/file.aspx?f=220875,"['Attard', 'Attard']","[(2976, 2982, 'LOC'), (3322, 3328, 'LOC')]"
6383,https://www.independent.com.mt/articles/2022-0...,European Climate Pact: Time to share your idea...,24/01/2022 13:45,The world is facing the worst known climate em...,https://www.independent.com.mt/file.aspx?f=220874,['Valletta'],"[(1206, 1214, 'LOC')]"
6386,https://www.independent.com.mt/articles/2022-0...,Three children detained illegally for 58 days ...,24/01/2022 13:03,Six people three of whom are minors were relea...,https://www.independent.com.mt/file.aspx?f=195597,"['Safi', 'Safi', 'Safi', 'Safi', 'Safi', 'Safi...","[(99, 103, 'LOC'), (931, 935, 'LOC'), (1580, 1..."
6395,https://www.independent.com.mt/articles/2022-0...,Getting to know… Emanuel Psaila – the man who ...,23/01/2022 10:30,The director general of the Civil Protection D...,https://www.independent.com.mt/file.aspx?f=220848,"['Żejtun', 'Kalkara', 'Munxar', 'Marsaxlokk', ...","[(1347, 1353, 'LOC'), (4082, 4089, 'LOC'), (42..."
6396,https://www.independent.com.mt/articles/2022-0...,50 Shades of Greats: ‘Life is beautiful’ - Fr ...,23/01/2022 10:00,Fr Hilary Tagliaferro was born in Tarxien on 2...,https://www.independent.com.mt/file.aspx?f=220822,"['Tarxien', 'Tarxien', 'Tarxien', 'Tarxien', '...","[(34, 41, 'LOC'), (738, 745, 'LOC'), (1038, 10..."

In [9]:
# write df2 to location_articles.csv
df2.to_csv('maltaindependent_location_articles.csv', index=False)